[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    " automatically download dll for windows
    let g:vimproc#download_windows_dll = 1
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ステータスバーの色をモードに応じて変更
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'istepura/vim-toolbar-icons-silk'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]] # 閉じ括弧を自動でつける 
repo = 'Townk/vim-autoclose'

[[plugins]] # 選択範囲を検索
repo = 'nelstrom/vim-visual-star-search'

[[plugins]] # comment out
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap <C-K> <Plug>(caw:hatpos:toggle)
  vmap <C-K> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = 'colorscheme hybrid'
[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
  nmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap <C-p> <Plug>(yankround-prev)
  nmap <C-n> <Plug>(yankround-next)
  let g:yankround_max_history = 100
  nnoremap <Leader><C-p> :<C-u>Unite yankround<CR>
'''

